@startuml
title Suchen und Zusammenfassen Impfdokumente
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Patient #red
participant "Portal" #00CC00
participant "Aggregator"
participant "Impfcheck" #red

participant "Gemeinschaften\nA..N" #00CC00

autonumber "<b>[00]"
Patient -> "Portal": Suche alle Impfdokumente
loop "Abfrage aller Gemeinschaften"
"Portal" -> "Gemeinschaften\nA..N": Suche nach Impfdokumenten
"Gemeinschaften\nA..N" -> "Portal": Alle gefundenen Impfdokumente (Gem A)
end
"Portal" -> "Aggregator": Zusammenfassen aller strukturierten Daten
"Aggregator" ->  "Portal": Ein aggregiertes Impfdokument
' "Portal" -> "Portal": Pseudonymisieren
"Portal" ->  "Impfcheck": aggregiertes Impfdokument
"Impfcheck" -> "Portal": Impfempfehlung
"Portal" -> Patient: Anzeigen der aggregierten\nImpfdaten

@enduml
