@startuml
title Rechercher et résumer les documents de vaccination
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor "Professionnel de la santé" AS Docteur #blue
participant "Portal" #00CC00
participant "[[aggregator.html Agrégateur de vaccins]]" as aggr

participant "Propre communauté\nA" #00CC00

participant "Autre communauté\nN" #00aaff


autonumber "<b>[00]"
Docteur -> "Portal": Rechercher les documents de vaccination
"Portal" -> "Propre communauté\nA": Rechercher dans les métadonnées
"Propre communauté\nA" -> "Portal": Métadonnées de tous les documents de vaccination
"Portal" -> "Propre communauté\nA": Consultation des documents de vaccination
"Propre communauté\nA" -> "Portal": Documents de vaccination

loop "Tous autres communautés"
"Portal" -> "Autre communauté\nN": Consultation des documents de vaccination
"Autre communauté\nN" -> "Portal": Documents de vaccination
end

"Portal" -> aggr: Résumer les documents de vaccination
aggr ->  "Portal": Un carnet de vaccination agrégé
"Portal" -> Docteur: Afficher les données de vaccination agrégées

@enduml
