@startuml
title Création du carnet de vaccination
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor "Professionnel de la santé" AS Docteur #blue
participant "Portal" #00CC00
participant "Propre communauté\nA" #00CC00
participant "Autre communauté\nN" #00aaff
participant "Certificate Service" #00aa00

autonumber "<b>[00]"
Docteur -> "Portal": Ajuster les données de vaccination agrégées,\ncréer un document de vaccination
"Portal" -> "Propre communauté\nA": Enregistrez le nouveau document de vaccination\net remplacez les "anciens" documents
"Propre communauté\nA" -> "Portal": OK

loop
"Portal" -> "Autre communauté\nN": Définissez les "anciens" documents de vaccination sur "OBSOLETE"
"Autre communauté\nN" -> "Portal": OK
end

Docteur -> "Portal": Création du carnet de vaccination
"Portal" -> "Portal": Collecte des données pour le certificat
"Portal" -> "Certificate Service": envoyer les données
"Certificate Service" -> "Certificate Service": Créer un certificat
"Certificate Service" -> "Portal": Certificat de vaccination délivré
"Portal" -> "Portal": Enregistrement du certificat de vaccination
"Portal" -> Docteur: Confirmation d'enregistration

@enduml
