@startuml
title Impfzertifikat erstellen
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Arzt #blue
participant "GFPP/PIS" #00CC00
participant "Eigene Gemeinschaft\nA" #00CC00
participant "Andere Gemeinschaft\nN" #00aaff
participant "Certificate Service" #00aa00

autonumber "<b>[00]"
Arzt -> "GFPP/PIS": Anpassen der aggregierten Impfdaten,\nerstellen Impfdokument
"GFPP/PIS" -> "Eigene Gemeinschaft\nA": Speichern des neuen Impfdokument\nund ersetzen der "alten" Dokumente
"Eigene Gemeinschaft\nA" -> "GFPP/PIS": OK

loop
"GFPP/PIS" -> "Andere Gemeinschaft\nN": Setzen der "alten" Impfdokumente auf "VERALTET"
"Andere Gemeinschaft\nN" -> "GFPP/PIS": OK
end

Arzt -> "GFPP/PIS": Erstellen des Impfzertifikats
"GFPP/PIS" -> "GFPP/PIS": Zusammenstellen der Daten für das Zertifikat
"GFPP/PIS" -> "Certificate Service": Senden der Daten
"Certificate Service" -> "Certificate Service": Erstellen Zertifikat
"Certificate Service" -> "GFPP/PIS": Erstelltes Impfzertifikat
"GFPP/PIS" -> "GFPP/PIS": Speichern des Impfzertifikats
"GFPP/PIS" -> Arzt: Bestätigung der Speicherung

@enduml
