@startuml
title Enregistrer et enregistrer la vaccination dans le DEP
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Docteur #blue
participant "GFPP/PIS" #00CC00
participant "Propre communauté\nA" #00CC00

autonumber "<b>[00]"
Docteur -> "GFPP/PIS": Enregistrez et sauvegardez\nla vaccination délivrée
"GFPP/PIS" -> "Propre communauté\nA": Enregistrez le document\n"Documentation de vaccination"
"Propre communauté\nA" -> "GFPP/PIS": OK

"GFPP/PIS" -> Docteur: Confirmation d'enregistration

@enduml
