@startuml
title Impfzertifikat
footer Version 1.0
skinparam responseMessageBelowArrow true

actor Arzt #blue
participant "GFPP/PIS" #00CC00
participant "Eigene Gemeinschaft A" #00CC00
participant "Andere Gemeinschaft N" #00aaff
participant "Certificate Service" #00aa00

autonumber "<b>[00]"
Arzt -> "GFPP/PIS": Anpassen der aggregierten Impfdaten,\nerstellen Impfdokument
"GFPP/PIS" -> "Eigene Gemeinschaft\nA": Speichern des neuen Impfdokument\nund ersetzen der "alten" Dokumente
"Eigene Gemeinschaft\nA" -> "GFPP/PIS": OK

loop
"GFPP/PIS" -> "Andere Gemeinschaft\nN": Setzen der "alten" Impfdokumente auf "VERALTET"
"Andere Gemeinschaft\nN" -> "GFPP/PIS": OK
end

"GFPP/PIS" -> Arzt: Bestätigung der Speicherung

@enduml
