@startuml
title Speichern eines aggregierten Documents de vaccinations im EPD
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Gesundheitsfachperson AS Arzt #blue
participant "Portal" #00CC00
participant "Eigene Gemeinschaft\nA" #00CC00
' participant "Andere Gemeinschaft\nB" #00aaff
' participant "Andere Gemeinschaft\nN" #00aaff

autonumber "<b>[00]"
Arzt -> "Portal": Anpassen der aggregierten Impfdaten,\nerstellen Impfdokument
"Portal" -> "Eigene Gemeinschaft\nA": Speichern des neuen Impfdokument
"Eigene Gemeinschaft\nA" -> "Portal": OK

' loop
' "GFPP/PIS" -> "Andere Gemeinschaft\nB": Setzen der "alten" Impfdokumente auf "VERALTET"
' "Andere Gemeinschaft\nB" -> "GFPP/PIS": OK

' "GFPP/PIS" -> "Andere Gemeinschaft\nN": Setzen der "alten" Impfdokumente auf "VERALTET"
' "Andere Gemeinschaft\nN" -> "GFPP/PIS": OK
' end
"Portal" -> Arzt: Bestätigung der Speicherung

@enduml
