@startuml
title Rechercher et résumer les documents de vaccination
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Patient #red
participant "Portal" #00CC00
participant "Propre communauté\nA" #00CC00

participant "[[aggregator.html Agrégateur de vaccins]]" as aggr
participant "Autre communauté\nB" #00aaff
participant "Autre communauté\nN" #00aaff


autonumber "<b>[00]"
Patient -> "Portal": Rechercher les documents de vaccination
"Portal" -> "Propre communauté\nA": Rechercher les documents de vaccination
"Propre communauté\nA" -> "Portal": Tous les documents de vaccination trouvés (Com A)
loop "Toutes les autres communautés"
"Portal" -> "Autre communauté\nB": Rechercher les documents de vaccination
"Autre communauté\nB" -> "Portal": Tous les documents de vaccination trouvés (Com B)

"Portal" -> "Autre communauté\nN": Rechercher les documents de vaccination
"Autre communauté\nN" -> "Portal": Tous les documents de vaccination trouvés (Com N)
end
"Portal" -> aggr: Résumer les documents de vaccination
aggr ->  "Portal": Un carnet de vaccination agrégé
"Portal" -> Patient: Afficher l'agrégat\nDates de vaccination

@enduml
