@startuml
title Impfzertifikat erstellen
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Gesundheitsfachperson AS Arzt #blue
participant "Portal" #00CC00
participant "Eigene Gemeinschaft\nA" #00CC00
participant "Andere Gemeinschaft\nN" #00aaff
participant "Certificate Service" #00aa00

autonumber "<b>[00]"
Arzt -> "Portal": Anpassen der aggregierten Impfdaten,\nerstellen Impfdokument
"Portal" -> "Eigene Gemeinschaft\nA": Speichern des neuen Impfdokument\nund ersetzen der "alten" Dokumente
"Eigene Gemeinschaft\nA" -> "Portal": OK

loop
"Portal" -> "Andere Gemeinschaft\nN": Setzen der "alten" Impfdokumente auf "VERALTET"
"Andere Gemeinschaft\nN" -> "Portal": OK
end

Arzt -> "Portal": Erstellen des Impfzertifikats
"Portal" -> "Portal": Zusammenstellen der Daten für das Zertifikat
"Portal" -> "Certificate Service": Senden der Daten
"Certificate Service" -> "Certificate Service": Erstellen Zertifikat
"Certificate Service" -> "Portal": Erstelltes Impfzertifikat
"Portal" -> "Portal": Speichern des Impfzertifikats
"Portal" -> Arzt: Bestätigung der Speicherung

@enduml
