@startuml
title Suchen und Zusammenfassen Impfdokumente
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Gesundheitsfachperson #blue
participant "Portal" #00CC00
participant "Aggregator"

participant "Eigene Gemeinschaft\nA" #00CC00

participant "Andere Gemeinschaft\nN" #00aaff


autonumber "<b>[00]"
Gesundheitsfachperson -> "Portal": Abfrage der Impfdokumente
"Portal" -> "Eigene Gemeinschaft\nA": Suche in den Metadaten
"Eigene Gemeinschaft\nA" -> "Portal": Metadaten aller Impfdokumente
"Portal" -> "Eigene Gemeinschaft\nA": Abfrage der Impfdokumente
"Eigene Gemeinschaft\nA" -> "Portal": Impfdokumente

loop "Alle anderen Gemeinschaften"
"Portal" -> "Andere Gemeinschaft\nN": Abfrage der Impfdokumente
"Andere Gemeinschaft\nN" -> "Portal": Impfdokumente
end

"Portal" -> "Aggregator": Zusammenfassen der Daten
"Aggregator" ->  "Portal": Ein aggregiertes Impfdokument
"Portal" -> Gesundheitsfachperson: Anzeigen der aggregierten\nImpfdaten

@enduml
