@startuml
title Suchen und Zusammenfassen Impfdokumente
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Arzt #blue
participant "GFPP/PIS" #00CC00
participant "Impfaggregator"
participant "Impfcheck" #red

participant "Gemeinschaften\nA..N" #00CC00

autonumber "<b>[00]"
Arzt -> "GFPP/PIS": Suche alle Impfdokumente
loop "Abfrage aller Gemeinschaften"
"GFPP/PIS" -> "Gemeinschaften\nA..N": Suche nach Impfdokumenten
"Gemeinschaften\nA..N" -> "GFPP/PIS": Alle gefundenen Impfdokumente (Gem A)
end
"GFPP/PIS" -> "Impfaggregator": Zusammenfassen aller strukturierten Daten
"Impfaggregator" ->  "GFPP/PIS": Ein aggregiertes Impfdokument
' "GFPP/PIS" -> "GFPP/PIS": Pseudonymisieren
"GFPP/PIS" ->  "Impfcheck": aggregiertes Impfdokument
"Impfcheck" -> "GFPP/PIS": Impfempfehlung
"GFPP/PIS" -> Arzt: Anzeigen der aggregierten\nImpfdaten

@enduml
