@startuml
title Suchen und Zusammenfassen Impfdokumente
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Arzt #blue
participant "PIS/Portal" #00CC00
participant "Aggregator"

participant "Eigene Gemeinschaft\nA" #00CC00

participant "Andere Gemeinschaft\nN" #00aaff


autonumber "<b>[00]"
Arzt -> "PIS/Portal": Abfrage der Impfdokumente
"PIS/Portal" -> "Eigene Gemeinschaft\nA": Suche in den Metadaten
"Eigene Gemeinschaft\nA" -> "PIS/Portal": Metadaten aller Impfdokumente
"PIS/Portal" -> "Eigene Gemeinschaft\nA": Abfrage der Impfdokumente
"Eigene Gemeinschaft\nA" -> "PIS/Portal": Impfdokumente

loop "Alle anderen Gemeinschaften"
"PIS/Portal" -> "Andere Gemeinschaft\nN": Abfrage der Impfdokumente
"Andere Gemeinschaft\nN" -> "PIS/Portal": Impfdokumente
end

"PIS/Portal" -> "Impfaggregator": Zusammenfassen der Daten
"Impfaggregator" ->  "PIS/Portal": Ein aggregiertes Impfdokument
"PIS/Portal" -> Arzt: Anzeigen der aggregierten\nImpfdaten

@enduml
