@startuml
title Rechercher et résumer les documents de vaccination
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Patient #red
participant "GFPP/PIS" #00CC00
participant "Propre communauté\nA" #00CC00

participant "agrégateur de vaccins"
participant "Autre communauté\nB" #00aaff
participant "Autre communauté\nN" #00aaff


autonumber "<b>[00]"
Patient -> "GFPP/PIS": Rechercher les documents de vaccination
"GFPP/PIS" -> "Propre communauté\nA": Rechercher les documents de vaccination
"Propre communauté\nA" -> "GFPP/PIS": Tous les documents de vaccination trouvés (Com A)
loop "Toutes les autres communautés"
"GFPP/PIS" -> "Autre communauté\nB": Rechercher les documents de vaccination
"Autre communauté\nB" -> "GFPP/PIS": Tous les documents de vaccination trouvés (Com B)

"GFPP/PIS" -> "Autre communauté\nN": Rechercher les documents de vaccination
"Autre communauté\nN" -> "GFPP/PIS": Tous les documents de vaccination trouvés (Com N)
end
"GFPP/PIS" -> "agrégateur de vaccins": Résumer les documents de vaccination
"agrégateur de vaccins" ->  "GFPP/PIS": Un carnet de vaccination agrégé
"GFPP/PIS" -> patient: Afficher l'agrégat\nDates de vaccination

@enduml
