@startuml
title Enregistrer et enregistrer la vaccination dans le DEP
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor "Professionnel de la santé" AS Docteur #blue
participant "Portal" #00CC00
participant "Propre communauté\nA" #00CC00

autonumber "<b>[00]"
Docteur -> "Portal": Enregistrez et sauvegardez\nla vaccination délivrée
"Portal" -> "Propre communauté\nA": Enregistrez le document\n"Documentation de vaccination"
"Propre communauté\nA" -> "Portal": OK

"Portal" -> Docteur: Confirmation d'enregistration

@enduml
