@startuml
title Suchen und Zusammenfassen Impfdokumente
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor Patient #red
participant "Portal" #00CC00
participant "Eigene Gemeinschaft\nA" #00CC00

participant "Impfaggregator"
participant "Andere Gemeinschaft\nB" #00aaff
participant "Andere Gemeinschaft\nN" #00aaff


autonumber "<b>[00]"
Patient -> "Portal": Suche alle Impfdokumente
"Portal" -> "Eigene Gemeinschaft\nA": Suche nach Impfdokumenten
"Eigene Gemeinschaft\nA" -> "Portal": Alle gefundenen Impfdokumente (Gem A)
loop "Alle anderen Gemeinschaften"
"Portal" -> "Andere Gemeinschaft\nB": Suche nach Impfdokumenten
"Andere Gemeinschaft\nB" -> "Portal": Alle gefundenen Impfdokumente (Gem. B)

"Portal" -> "Andere Gemeinschaft\nN": Suche nach Impfdokumenten
"Andere Gemeinschaft\nN" -> "Portal": Alle gefundenen Impfdokumente (Gem. N)
end
"Portal" -> "Impfaggregator": Zusammenfassen aller strukturierten Daten
"Impfaggregator" ->  "Portal": Ein aggregiertes Impfdokument
"Portal" -> Patient: Anzeigen der aggregierten\nImpfdaten

@enduml
