@startuml
title Enregistrer et enregistrer la vaccination dans le DEP
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor "Patient ou\nPatiente" as pat #red
participant "Portal" #00CC00
participant "Propre communauté\nA" #00CC00

autonumber "<b>[00]"
pat -> "Portal": Enregistrez et sauvegardez\nla vaccination délivrée
"Portal" -> "Propre communauté\nA": Enregistrez le document\n"Documentation de vaccination"
"Propre communauté\nA" -> "Portal": OK

"Portal" -> pat: Confirmation d'enregistration

@enduml
