@startuml
title Enregistrement d'un document de vaccination agrégé dans le DEP
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor "Professionnel de la santé" AS Docteur #blue
participant "Portal" #00CC00
participant "Propre communauté\nA" #00CC00
' participant "Autre communauté\nB" #00aaff
' participant "Autre communauté\nN" #00aaff

autonumber "<b>[00]"
Docteur -> "Portal": Ajuster les données de vaccination agrégées,\créer un document de vaccination
"Portal" -> "Propre communauté\nA": Enregistrez le nouveau document de vaccination
"Propre communauté\nA" -> "Portal": OK

' loop
' "GFPP/PIS" -> "Autre communauté\nB": Définissez les "anciens" Documents de vaccination sur "OBSOLETE"
' "Autre communauté\nB" -> "GFPP/PIS": OK

' "GFPP/PIS" -> "Autre communauté\nN": Définissez les "anciens" Documents de vaccination sur "OBSOLETE"
' "Autre communauté\nN" -> "GFPP/PIS": OK
' end
"Portal" -> Docteur: Confirmation d'enregistration

@enduml
