@startuml
title Save a vaccination document in EPD
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width

actor HCP #blue
box "Community A"
participant "GFPP/PIS" #00CC00
participant "CO-Repository" #00CC00
participant "CO-Registry" #00CC00
participant "CO-IGW" #00CC00
end box
box "Community X"
participant "OC-RGW" #00aaff
participant "OC-Registry" #00aaff
end box

autonumber "<b>[00]"
HCP -> "GFPP/PIS": Change data and store it
activate "GFPP/PIS"
"GFPP/PIS" -> "GFPP/PIS": Create FHIR ch-vacd Document
"GFPP/PIS" -> "CO-Repository": Provide and Register Document\nSet Request [ITI-41]
activate "CO-Repository"
"CO-Repository" -> "CO-Registry": Register Document Set\nRequest [ITI-41]
activate "CO-Registry"
"CO-Registry" -> "CO-Repository": Register Document Set\nResponse [ITI-41]
deactivate "CO-Registry"
"CO-Repository" -> "GFPP/PIS": Provide and Register Document\nSet Response [ITI-41]
deactivate "CO-Repository"

"GFPP/PIS" -> "GFPP/PIS": set all old documents to deprecated
activate "GFPP/PIS"
loop "all other communities"
"GFPP/PIS" -> "CO-IGW": Restricted Metadata Update Request [ITI-92]
activate "CO-IGW"

"CO-IGW" -> "OC-RGW": Restricted Metadata Update\nRequest [ITI-92]
activate "OC-RGW"
"OC-RGW" -> "OC-Registry": Restricted Metadata Update\nRequest [ITI-92]
activate "OC-Registry"
"OC-Registry" -> "OC-RGW": Restricted Metadata Update\nResponse [ITI-92]
deactivate "OC-Registry"
"OC-RGW" -> "CO-IGW": Restricted Metadata Update\nResponse [ITI-92]
deactivate "OC-RGW"
"CO-IGW" -> "GFPP/PIS": Restricted Metadata Update Response [ITI-92]
deactivate "CO-IGW"
end
"GFPP/PIS" -> "GFPP/PIS": OK
deactivate "GFPP/PIS"

"GFPP/PIS" -> HCP: Show success message
deactivate "GFPP/PIS"
@enduml
