@startuml
title Aggregation of Immunization Administration Documents with duplicate

'left to right direction


object "Immunization Administration\nDocument 1" as Doc1b #lightblue
Doc1b : entry "Immunization1"

object "Immunization Administration\nDocument 2" as Doc2b #lightblue
Doc2b : entry "Immunization 1"

object "Immunization Administration\nDocument 3" as Doc3b #lightblue
Doc3b : entry "Immunization 2"

object "Aggregator" as AGG3

object "Vaccination Record\nDocument" as RES3 #lightgreen
RES3 : entry "Immunization 1 - duplicate error reference"
RES3 : entry "Immunization 1 - duplicate error reference"
RES3 : entry "Immunization 2"


Doc1b -down-> AGG3
Doc2b -down-> AGG3
Doc3b -down-> AGG3
AGG3 -down-> RES3

@enduml