@startuml
skinparam shadowing false
skinparam rectangle {
    roundCorner 10
}

skinparam linetype straight
skinparam defaultFontSize 12

left to right direction

rectangle "[[StructureDefinition-ch-vacd-recommendation-response-message.html Bundle: Immunization Recommendation Response Message]]" as document #Orange {
    rectangle "[[StructureDefinition-ch-vacd-recommendation-response-messageheader.html Entry: Immunization Recommendation Response MessageHeader]]" as composition #Lightblue  {
        together {
            rectangle sender
            rectangle destination.receiver
            rectangle responsible
        }

        together {
            card focus {
                card focus1
                card focus2
                card focus3
                card focus4
            }
        }

    }

    together {
        rectangle "[[http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-organization-epr Entry: Organization]]" as labor1 #ec4d4dff {
            ''card name1 [
            ''----
            ''labor
            '']
        }

        rectangle "[[http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-practitionerrole-epr Entry: PractitionerRole]]" as practitionerrole #ec4d4dff {
            ''card practitioner as practitioner1
            ''card organization as organization1
        }
        rectangle "[[http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-practitioner-epr Entry: Practitioner]]" as practitioner #ec4d4dff {
            ''card name2 [
            ''----
            ''dr. med. hausarzt
            '']
        }
        rectangle "[[http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-organization-epr Entry: Organization]]" as organization #ec4d4dff {
            ''card name3 [
            ''----
            ''praxis
            '']
        }

        rectangle "[[http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient-epr Entry: Patient]]" as patient #ec4d4dff {
        }

        rectangle "[[StructureDefinition-ch-vacd-immunization-recommendation.html Entry: ImmunizationRecommendation]]" as immunizationrecommendation1 #ec4d4dff {
        }
        rectangle "[[StructureDefinition-ch-vacd-immunization-recommendation.html Entry: ImmunizationRecommendation]]" as immunizationrecommendation2 #ec4d4dff {
        }
        rectangle "[[StructureDefinition-ch-vacd-immunization-recommendation.html Entry: ImmunizationRecommendation]]" as immunizationrecommendation3 #ec4d4dff {
        }

    }
}

focus1 "Reference"..> patient
focus2 "Reference"..> immunizationrecommendation1
focus3 "Reference"..> immunizationrecommendation2
focus4 "Reference"..> immunizationrecommendation3

sender "Reference"..> labor1
responsible "Reference"..> labor1


destination.receiver "Reference"..> practitionerrole
practitionerrole ..>"practitioner: Reference" practitioner
practitionerrole ..>"organization: Reference" organization

@enduml