@startuml
title Test Case 01
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width


box "Stammgemeinschaft (G1)"
actor PAT #blue
actor GFP1_G1 #lightblue
participant "Dok1\nAdmin" #lightblue
participant "Dok2\nAdmin" #lightblue
participant Aggregator
participant "Resultat\nRecord" #lightgreen
end box

box "Gemeinschaft (G2)"
participant "Dok3\nAdmin" #orange
actor GFP2_G2 #orange
end box

PAT -> "Dok1\nAdmin": Patient (G1) erstellt Dokument\nfür Impfung mit Havrix 1440 gegen Hepatitis A

GFP1_G1 -> "Dok2\nAdmin": Gesundheitsfachperson (G1) erstellt Dokument\nfür Impfung mit Boostrix gegen Diphterie, Tetanus und Keuchhusten

GFP2_G2 -> "Dok3\nAdmin": Gesundheitsfachperson (G2) erstellt Dokument\nfür Impfung mit FSME-Immun CC gegen FSME (1. Dosis)

"Dok1\nAdmin" -> Aggregator: aggregation
"Dok2\nAdmin" -> Aggregator: aggregation
"Dok3\nAdmin" -> Aggregator: aggregation
Aggregator -> "Resultat\nRecord": Erstellt Record Dokument
PAT -> "Resultat\nRecord": Patient schaut die Impfübersicht an


@enduml
