@startuml
title Test Case 03
footer Version 1.0
skinparam responseMessageBelowArrow true
scale max 800 width


box "Stammgemeinschaft (G1)"
actor PAT #blue
participant "Dok1\nAdmin" #lightblue
participant "Dok2\nAdmin" #lightblue
participant "Dok5\nAdmin" #lightblue
participant Aggregator
participant "Resultat\nRecord" #lightgreen
end box

PAT -> "Dok5\nAdmin": Patient erstellt Dokument\nfür Impfung mit FSME-Immun CC gegen FSME (2. Dosis)

box "Gemeinschaft (G2)"
participant "Dok3\nAdmin" #orange
participant "Dok4\nAdmin" #orange
end box



"Dok1\nAdmin" --> Aggregator: zusammenfügen
"Dok2\nAdmin" --> Aggregator: zusammenfügen
"Dok3\nAdmin" --> Aggregator: zusammenfügen
"Dok4\nAdmin" --> Aggregator: zusammenfügen
"Dok5\nAdmin" --> Aggregator: zusammenfügen
Aggregator -> "Resultat\nRecord": Erstellt Record Dokument
PAT -> "Resultat\nRecord": Patient schaut die Impfübersicht an


@enduml
