@startuml
title Test Case 04
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width


box "Stammgemeinschaft (G1)"
actor "Patient" as PAT #blue
actor "GFP1 G1" as GFP1 #lightblue
participant "Dok1\nAdmin" as Dok1 #lightblue
participant "Dok2\nAdmin" as Dok2 #lightblue
participant "Dok5\nAdmin" as Dok5 #lightblue
participant "Dok6\nAdmin" as Dok6 #lightblue
participant "Aggregator" as AG
participant "Resultat\nRecord" AS RES #lightgreen
end box

GFP1 -> Dok6: GFP validiert die FSME Impfung des Patienten\nund erstellt Dokument damit Impfung mit FSME-Immun CC\ngegen FSME (2. Dosis) validiert ist
Dok6 --> Dok5 : relatesTo

box "Gemeinschaft (G2)"
participant "Dok3\nAdmin" as Dok3 #orange
participant "Dok4\nAdmin" as Dok4 #orange
end box



Dok1 --> AG: zusammenfügen
Dok2 --> AG: zusammenfügen
Dok3 --> AG: zusammenfügen
Dok4 --> AG: zusammenfügen
Dok5 --> AG: zusammenfügen
Dok6 --> AG: zusammenfügen
AG -> RES: Erstellt Record Dokument
PAT -> RES: Patient schaut die Impfübersicht an


@enduml
