@startuml
title Test Case A 03
footer Version 2.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width

box "eHealth Record Repository 1"
actor "Practitioner" as PAT #red
participant "[[Bundle-A-D1-P-C1.html Doc1\nAdmin\nA-D1-P-C1]]" as Doc1 #lightblue
participant "[[Bundle-A-D2-HCP1-C1.html Doc2\nAdmin\nA-D2-HCP1-C1]]" as Doc2 #lightblue
participant "[[Bundle-A-D5-P-C1.html Doc5\nAdmin\nA-D5-P-C1]]" as Doc5 #lightblue
participant "[[aggregator.html Aggregator]]" as AGG
participant "[[Bundle-RDA03b.html Resultat\nRecord\nRDA03b]]" as RES #lightgreen
end box

PAT -> Doc5: Patient (C1) creates document\nwith vaccination FSME-Immun CC against TBE (2nd dose)
PAT <-- Doc5

box "eHealth Record Repository 2"
participant "[[Bundle-A-D3-HCP2-C2.html Doc3\nAdmin\nA-D3-HCP2-C2]]" as Doc3 #orange
participant "[[Bundle-A-D4-HCP2-C2.html Doc4\nAdmin\nA-D4-HCP2-C2]]" as Doc4 #orange
end box

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc1: get Doc1
AGG <-- Doc1

AGG -> Doc2: get Doc2
AGG <-- Doc2

AGG -> Doc3: get Doc3
AGG <-- Doc3
AGG -> Doc4: get Doc4
AGG <-- Doc4

AGG -> Doc5: get Doc5
AGG <-- Doc5

AGG -> AGG: aggregate documents 
AGG -> AGG: add document author (Practitioner or Device)
activate AGG
AGG -> RES: create Vaccination Record
deactivate AGG
AGG <-- RES

PAT <-- AGG: Show Vaccination Record
deactivate AGG

@enduml
