@startuml
title Test Case A 03
footer Version 2.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width

box "Reference Community (C1)"
actor "Practitioner" as PAT #red
participant "Doc1\nAdmin" as Doc1 #lightblue
participant "Doc2\nAdmin" as Doc2 #lightblue
participant "Doc5\nAdmin" as Doc5 #lightblue
participant Aggregator as AGG
participant "Resultat\nRecord" as RES #lightgreen
end box

PAT -> Doc5: Patient (C1) creates document\nwith vaccination FSME-Immun CC against TBE (2nd dose)
PAT <-- Doc5

box "Community (C2)"
participant "Doc3\nAdmin" as Doc3 #orange
participant "Doc4\nAdmin" as Doc4 #orange
end box

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc1: get Doc1
AGG <-- Doc1

AGG -> Doc2: get Doc2
AGG <-- Doc2

AGG -> Doc3: get Doc3
AGG <-- Doc3
AGG -> Doc4: get Doc4
AGG <-- Doc4

AGG -> Doc5: get Doc5
AGG <-- Doc5

AGG -> AGG: aggregate documents 
AGG -> AGG: add document author (Practitioner or Device)
activate AGG
AGG -> RES: create Vaccination Record
deactivate AGG
AGG <-- RES

PAT <-- AGG: Show Vaccination Record
deactivate AGG

@enduml
