@startuml
title Test Case A 01
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width


box "Reference Community (C1)"
actor "Health Care Professional 1 (C1)" as HCP1_C1 #red
actor "Patient" as PAT #blue
participant "Doc1\nAdmin" as Doc1 #lightblue
participant "Doc2\nAdmin" as Doc2 #lightblue
participant Aggregator as AGG
participant "Result\nRecord" as RES #lightgreen
end box

box "Community (C2)"
participant "Doc3\nAdmin" as Doc3 #orange
actor "Health Care Professional 2 (C2)" as HCP2_C2 #orange
end box

PAT -> Doc1: Patient (C1) creates document\nwith vaccination Havrix 1440 against viral heaptite A
PAT <-- Doc1

HCP1_C1 -> Doc2: HCP1 (C1) creates document\nwith vaccination Boostrix against\nDiphteria, Tetanus and pertussis
HCP1_C1 <-- Doc2

HCP2_C2 -> Doc3: HCP2 (G2) creates document\nwith vaccination FSME-Immun CC\nagainst TBE (1. Dosis)
HCP2_C2 <-- Doc3:

HCP1_C1 -> AGG: get Vaccination Record
activate AGG
AGG -> Doc1: get doc
AGG <-- Doc1
AGG -> Doc2: get doc
AGG <-- Doc2
AGG -> Doc3: get doc
AGG <-- Doc3

AGG -> AGG: aggregate
activate AGG
AGG -> AGG: add document author (Practitioner or Device)
AGG -> RES: creates document\nVaccination Record 
deactivate AGG
AGG <-- RES
HCP1_C1 <-- AGG: show Vaccination Record
deactivate AGG


@enduml
