@startuml
title Test Case A 02
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width


box "Reference Community (C1)"
actor "Patient" as PAT #blue
participant "Doc1\nAdmin" as Doc1 #lightblue
participant "Doc2\nAdmin" as Doc2  #lightblue
participant Aggregator as AGG
participant "Resultat\nRecord" as RES #lightgreen
end box

box "Community (C2)"
participant "Doc3\nAdmin" as Doc3 #orange
participant "Doc4\nAdmin" as Doc4 #orange
actor "Health Care Professional 2 (C2)" as HCP2_C2 #orange
end box

HCP2_C2 -> Doc4: HCP2 (G2) creates document\nwith vaccination Havrix 1440 against viral heaptite A (2nd dose)
HCP2_C2 <-- Doc4

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc1: get doc
AGG <-- Doc1

AGG -> Doc2: get doc
AGG <-- Doc2

AGG -> Doc3: get doc
AGG <-- Doc3

AGG -> Doc4: get doc
AGG <-- Doc4

AGG -> AGG: aggregate
activate AGG
AGG -> AGG: add author (Patient or Device)
AGG -> RES: creates document\nVaccination Record
deactivate AGG
AGG <-- RES
PAT <-- AGG: show Vaccination Record
deactivate AGG

@enduml
