@startuml
title Test Case A 04
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width

box "Reference Community (C1)"
actor "Patient" as PAT #blue
actor "Health Care Professional 1 (C1)" as HCP1_C1 #lightblue
participant "Doc1\nAdmin" as Doc1 #lightblue
participant "Doc2\nAdmin" as Doc2 #lightblue
participant "Doc5\nAdmin" as Doc5 #lightblue
participant "Doc6\nAdmin" as Doc6 #lightblue
participant Aggregator as AGG
participant "Resultat\nRecord" as RES #lightgreen
end box


HCP1_C1 -> Doc6: HCP1 validates the TBE vaccination of the patient \n and creates a document so that the vaccination with FSME-Immun CC\nagainst TBE (2nd dose) is validated
HCP1_C1 <-- Doc6
Doc6 o<-[#red]->o Doc5: relatesTo 

box "Community (C2)"
participant "Doc3\nAdmin" as Doc3 #orange
participant "Doc4\nAdmin" as Doc4 #orange
end box

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc1: get doc
AGG <-- Doc1

AGG -> Doc2: get doc
AGG <-- Doc2

AGG -> Doc3: get doc
AGG <-- Doc3

AGG -> Doc4: get doc
AGG <-- Doc4

AGG -> Doc3: get doc
AGG <-- Doc5

AGG -> Doc3: get doc
AGG <-- Doc6

AGG -> AGG: aggregate documents 
activate AGG
AGG -> AGG: add document author (Patient or Device)
AGG -> RES: create Vaccination Record
deactivate AGG
AGG <-- RES

PAT <-- AGG: show Vaccination Record
deactivate AGG


@enduml
