@startuml
title Test Case B 04
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width

box "eHealth Record Repository 1"
actor "Patient" as PAT #blue
actor "Health Care Professional 1 (R1)" as HCP1_C1 #lightblue
participant "[[Bundle-B-D1-HCP1-C1.html Doc1\nAdmin\nB-D1-HCP1-C1]]" as Doc1 #lightblue
participant "[[Bundle-B-D5-HCP1-C1.html Doc5\nAdmin\nB-D5-HCP1-C1]]" as Doc5 #lightblue
participant "[[aggregator.html Aggregator]]" as AGG
participant "[[Bundle-RDB04.html Result\nRecord\nRDB04]]" as RES #lightgreen
end box

HCP1_C1 -> Doc1: HCP1 (C1) creates document\nwith vaccination Boostrix and FSME CC
HCP1_C1 <-- Doc1

HCP1_C1 -> Doc5: HCP1 (C1) creates document\nwith an entry for laboratory and\nserology result
HCP1_C1 <-- Doc5

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc1: get doc
AGG <-- Doc1

AGG -> Doc5: get doc
AGG <-- Doc5
 
AGG -> AGG: aggregate documents 
activate AGG
AGG -> AGG: add document author (Patient or Device)
AGG -> RES: create Vaccination Record
deactivate AGG
AGG <-- RES

PAT <-- AGG: show Vaccination Record
deactivate AGG


@enduml
