@startuml
title Test Case C 03
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width

box "eHealth Record Repository 1"
actor "Patient" as PAT #blue
actor "Health Care Professional 1 (R1)" as HCP1_C1 #lightblue
participant "[[Bundle-B-D4-HCP1-C1.html Doc4\nAdmin\nB-D4-HCP1-C1]]" as Doc4 #lightblue
participant "[[Bundle-C-D3-HCP1-C1.html Doc3\nAdmin\nC-D3-HCP1-C1]]" as Doc3 #lightblue
participant "[[aggregator.html Aggregator]]" as AGG
participant "[[Bundle-RDC03.html Result\nRecord\nRDC03]]" as RES #lightgreen
end box

HCP1_C1 -> Doc4: HCP1 (C1) creates document with an entry\nfor exposition risk "Worker in HealthCare"
HCP1_C1 <-- Doc4

HCP1_C1 -> Doc3: HCP1 (C1) creates document with cancelation\n of entry exposition risk "Worker in HealthCare"
HCP1_C1 <-- Doc3

Doc3 o<-[#red]->o Doc4: Has entered-in-error relation

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc4: get doc
AGG <-- Doc4

AGG -> Doc3: get doc
AGG <-- Doc3
 
AGG -> AGG: aggregate documents 
activate AGG
AGG -> AGG: add document author (Patient or Device)
AGG -> RES: create Vaccination Record
deactivate AGG
AGG <-- RES

PAT <-- AGG: show Vaccination Record
deactivate AGG


@enduml
