@startuml
title Test Case D 02
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width

box "eHealth Record Repository 1"
actor "Patient" as PAT #blue
participant "[[Bundle-D-D3-HCP1-C1.html Doc3\nAdmin\nD-D3-HCP1-C1]]" as Doc3 #lightblue
participant "[[aggregator.html Aggregator]]" as AGG
participant "[[Bundle-RDD02.html Result\nRecord\nRDD02]]" as RES #lightgreen
end box

box "eHealth Record Repository 2"
participant "[[Bundle-D-D4-HCP2-C2.html Doc4\nAdmin\nD-D4-HCP2-C2]]" as Doc4 #orange
end box

Doc3 --> AGG: aggregation
Doc4 --> AGG: aggregation

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc3: get doc
AGG <-- Doc3

AGG -> Doc4: get doc
AGG <-- Doc4
 
AGG -> AGG: aggregate documents 
activate AGG

Doc3 o<-[#red]->o Doc4: Same Immunization entry detected
Doc3 o<-[#red]->o Doc4: Same PastIllness entry detected
Doc3 o<-[#red]->o Doc4: Same MedicalRisk entry detected

AGG -> AGG: add double entries error
AGG -> AGG: add document author (Patient or Device)
AGG -> RES: create Vaccination Record
deactivate AGG
AGG <-- RES

PAT <-- AGG: show Vaccination Record
deactivate AGG


@enduml
