@startuml
title Test Case D 01
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width

box "Reference Community (C1)"
actor "Patient" as PAT #blue
participant "Doc1\nAdmin" as Doc1 #lightblue
participant Aggregator as AGG
participant "Result\nRecord" as RES #lightgreen
end box

box "Community (C2)"
participant "Doc2\nAdmin" as Doc2 #orange
end box

Doc1 --> AGG: aggregation
Doc2 --> AGG: aggregation

Doc1 <-> Doc2: Same Immunization entry detected

AGG -> RES: creates document\nVaccination Record 
PAT -> RES: Patient sees immunization status


@enduml
