@startuml
title Test Case E 01
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width


box "Reference Community (C1)"
actor "Patient" as PAT #blue
actor "Health Care Professional 1 (C1)" as HCP1_C1 #lightblue
participant "Doc1\nAdmin" as Doc1 #lightblue
participant "Doc2\nAdmin" as Doc2 #lightblue
participant Aggregator as AGG
participant "Result\nRecord" as RES #lightgreen
end box

HCP1_C1 -> Doc1: HCP1 (C1) creates document\nwith vaccinations in the language fr-CH
HCP1_C1 <-- Doc1

HCP1_C1 -> Doc2: HCP1 (C1) creates document\nwith an entry for past illness in the language en-US
HCP1_C1 <-- Doc2

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc1: get doc
AGG <-- Doc1

AGG -> Doc2: get doc
AGG <-- Doc2
 
AGG -> AGG: aggregate documents 
activate AGG
AGG -> AGG: add document author (Patient or Device)
AGG -> RES: create Vaccination Record
deactivate AGG
AGG <-- RES

PAT <-- AGG: show Vaccination Record
deactivate AGG


@enduml
