@startuml
title Test Case F 02
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width

box "eHealth Record Repository 1"
actor "Patient" as PAT #blue
actor "Health Care Professional 1 (R1)" as HCP1_C1 #lightblue
participant "[[Bundle-F-D3-HCP1-C1.html Doc3\nAdmin\nF-D3-HCP1-C1]]" as Doc3 #lightblue
participant "[[Bundle-F-D4-HCP1-C1.html Doc4\nAdmin\nF-D4-HCP1-C1]]" as Doc4 #lightblue
participant "[[aggregator.html Aggregator]]" as AGG
participant "[[Bundle-RDF02.html Result\nRecord\nRDF02]]" as RES #lightgreen
end box

HCP1_C1 -> Doc3: Practitoner (HCP1_C1) creates document\nwith allergy entry.
HCP1_C1 <-- Doc3

HCP1_C1 -> Doc4: Practitoner (HCP1_C1) creates document\nadding a comment (note) to the allergy entry.
HCP1_C1 <-- Doc4

Doc4 o<-[#red]->o Doc3: Has replacement relation

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc3: get doc
AGG <-- Doc3

AGG -> Doc4: get doc
AGG <-- Doc4
 
AGG -> AGG: aggregate documents 
activate AGG
AGG -> AGG: add document author (Patient or Device)
AGG -> RES: create Vaccination Record
deactivate AGG
AGG <-- RES

PAT <-- AGG: show Vaccination Record
deactivate AGG


@enduml
