@startuml
title Test Case F 03
footer Version 1.0
skinparam responseMessageBelowArrow true
skinparam style strictuml
scale max 800 width

box "eHealth Record Repository 1"
actor "Patient" as PAT #blue
actor "Health Care Professional 1 (R1)" as HCP1_C1 #lightblue
participant "[[Bundle-F-D5-HCP1-C1.html Doc5\nAdmin\nF-D5-HCP1-C1]]" as Doc5 #lightblue
participant "[[Bundle-F-D6-HCP1-C1.html Doc6\nAdmin\nF-D6-HCP1-C1]]" as Doc6 #lightblue
participant "[[aggregator.html Aggregator]]" as AGG
participant "[[Bundle-RDF03.html Result\nRecord\nRDF03]]" as RES #lightgreen
end box

HCP1_C1 -> Doc5: Practitoner (HCP1_C1) creates document\nwith condition pastillness entry.
HCP1_C1 <-- Doc5

HCP1_C1 -> Doc6: Practitoner (HCP1_C1) creates document\nadding a comment (note) to the condition pastillness entry Havrix 1440.
HCP1_C1 <-- Doc6

Doc6 o<-[#red]->o Doc5: Has replacement relation

PAT -> AGG: get Vaccination Record
activate AGG

AGG -> Doc5: get doc
AGG <-- Doc5

AGG -> Doc6: get doc
AGG <-- Doc6
 
AGG -> AGG: aggregate documents 
activate AGG
AGG -> AGG: add document author (Patient or Device)
AGG -> RES: create Vaccination Record
deactivate AGG
AGG <-- RES

PAT <-- AGG: show Vaccination Record
deactivate AGG


@enduml
