@startuml
scale max 800 width
<style>
element {MinimumWidth 150}
</style>

|Médecin en interaction\navec le patient|
start
|#LightBlue|PIS|
:Le médecin met à jour\nles données vaccinales;
:Le médecin lance le\ncontrôle vaccinal;

|#AntiqueWhite|Contrôle vaccinal|
:Le contrôle vaccinal\naffiche le statut\nvaccinal;
:Le contrôle vaccinal\naffiche les\nrecommandations vaccinales;

|Médecin en interaction\navec le patient|
:Le médecin discute des\nrecommandations\navec le patient;
if (Le patient souhaite\nse faire vacciner) then (Oui)
  :Le médecin effectue\nla vaccination;
  |#LightBlue|PIS|
  :Le médecin documente\nla vaccination;
  |Médecin en interaction\navec le patient|
else (Non)
  |PIS|
  :Le médecin documente\nle motif du refus;
  |Médecin en interaction\navec le patient|
endif

stop

@enduml

