@startuml
scale max 800 width
<style>
element {MinimumWidth 200}
</style>

|Patient bzw. Patientin|
start
|#LightBlue|Impf-APP|
:Zeigt den aktuellen\nImpfstatus an;
:Patient aktualisiert\ndie Impfdaten; 
:Patient ruft\nImpfcheck auf;

|#AntiqueWhite|Impfcheck|
:Impfcheck zeigt\nImpfstatus an;
:Impfcheck zeigt\nEmpfehlungen an;

|Patient bzw. Patientin|
if (Patient möchte Impfung durchführen) then (Ja)
  :Patient macht einen\nTermin beim Arzt aus;
  |#LightSalmon|Gesundheitsfachperson in Interaktion\nmit Patient bzw. Patientin|
  :Gesundheitsfachperson\nführt Impfung durch;
  |#LightBlue|PIS|
  :Gesundheitsfachperson\ndokumentiert Impfung;
  |Patient bzw. Patientin|
  :Patient überprüft die\naktualisierten Impfdaten\nin der Impf-APP;
  |Impf-APP|
  :Zeigt den aktualisierten\nImpfstatus an;
else (Nein)

endif
|Patient bzw. Patientin|
stop


@enduml

