# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ch.fhir.ig.ch-vacd
canonical: http://fhir.ch/ig/ch-vacd
name: CH_VACD
title: Implementation Guide CH VACD
# FSHOnly: true
# applyExtensionMetadataToRoot: false
status: active
version: 5.0.0-ci-build
date: 2024-05-17
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: HL7 Switzerland
  url: https://www.hl7.ch/

license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# menu:
#   Home: index.html
#   Use Cases: usecases.html
#   Document: documents.html  
#   Profiles: profiles.html
#   Extensions: extensions.html
#   Terminology: terminology.html
#   Artifacts: artifacts.html
#   Test Cases: TestCases.html

parameters:
  excludettl: true
  display-warnings: true
  allow-extensible-warnings: true

  special-url:
    - urn:oid:2.16.756.5.30.1.127.3.10.10
    - urn:oid:0.4.0.127.0.16.1.1.2.1 # edqm-standardterms
    - urn:oid:2.51.1.1 # GTIN http://oidref.com/2.51.1.1


dependencies:
  hl7.terminology: 5.5.0
  ch.fhir.ig.ch-core: 5.0.0-ballot
  ch.fhir.ig.ch-term: 3.0.x
  hl7.fhir.uv.ips:
    version: 1.1.0
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
    id: ips

