Instance: 1-2-ImmunizationCertificate
InstanceOf: CHVACDDocumentImmunizationCertificate
Title: "1.2 Immunization Certificate"
Description: "Example for Bundle Immunization Certificate"
Usage: #example
* meta.lastUpdated = "2021-06-01T00:00:00.963+02:00"
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:5b8a26b2-dd6d-4c04-acaf-e4a44b7bcf47"
* type = #document
* timestamp = "2021-06-01T00:00:00.963+02:00"
* entry[0].fullUrl = "http://test.fhir.ch/r4/Composition/2-2-ImmunizationCertificateComposition"
* entry[=].resource = 2-2-ImmunizationCertificateComposition
* entry[+].fullUrl = "http://test.fhir.ch/r4/Patient/3-1-Patient"
* entry[=].resource = 3-1-Patient
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/4-1-Practitioner"
* entry[=].resource = 4-1-Practitioner
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/5-1-Organization"
* entry[=].resource = 5-1-Organization
* entry[+].fullUrl = "http://test.fhir.ch/r4/PractitionerRole/6-1-PractitionerRole"
* entry[=].resource = 6-1-PractitionerRole
* entry[+].fullUrl = "http://test.fhir.ch/r4/Binary/originalRepresentation1"
* entry[=].resource = originalRepresentation1
* entry[+].fullUrl = "http://test.fhir.ch/r4/PractitionerRole/6-2-PractitionerRole"
* entry[=].resource = 6-2-PractitionerRole
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/4-2-Practitioner"
* entry[=].resource = 4-2-Practitioner
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/5-2-Organization"
* entry[=].resource = 5-2-Organization
* entry[+].fullUrl = "http://test.fhir.ch/r4/PractitionerRole/6-3-PractitionerRole"
* entry[=].resource = 6-3-PractitionerRole
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/4-3-Practitioner"
* entry[=].resource = 4-3-Practitioner
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/5-3-Organization"
* entry[=].resource = 5-3-Organization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-2-Immunization"
* entry[=].resource = 7-2-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-3-Immunization"
* entry[=].resource = 7-3-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-4-Immunization"
* entry[=].resource = 7-4-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-5-Immunization"
* entry[=].resource = 7-5-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-6-Immunization"
* entry[=].resource = 7-6-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/8-4-Condition"
* entry[=].resource = 8-4-Condition
* entry[+].fullUrl = "http://test.fhir.ch/r4/AllergyIntolerance/11-1-AllergyIntolerance"
* entry[=].resource = 11-1-AllergyIntolerance
* entry[+].fullUrl = "http://test.fhir.ch/r4/AllergyIntolerance/11-2-AllergyIntolerance"
* entry[=].resource = 11-2-AllergyIntolerance