Instance: 1-3-VaccinationRecord
InstanceOf: CHVACDDocumentVaccinationRecord
Title: "1.3 Vaccination Record"
Description: "Example for Bundle Vaccination Record"
Usage: #example
* meta.lastUpdated = "2021-06-01T00:00:00.568+02:00"
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:5b8a26b2-dd6d-4c04-acaf-e4a44b7bcf47"
* type = #document
* timestamp = "2021-06-01T00:00:00.568+02:00"
* entry[0].fullUrl = "http://test.fhir.ch/r4/Composition/2-3-VaccinationRecordComposition"
* entry[=].resource = Inline-Instance-for-1-3-VaccinationRecord-1
* entry[+].fullUrl = "http://test.fhir.ch/r4/Patient/3-1-Patient"
* entry[=].resource = 3-1-Patient
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/4-1-Practitioner"
* entry[=].resource = 4-1-Practitioner
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/5-1-Organization"
* entry[=].resource = 5-1-Organization
* entry[+].fullUrl = "http://test.fhir.ch/r4/PractitionerRole/6-1-PractitionerRole"
* entry[=].resource = 6-1-PractitionerRole
* entry[+].fullUrl = "http://test.fhir.ch/r4/PractitionerRole/6-2-PractitionerRole"
* entry[=].resource = 6-2-PractitionerRole
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/4-2-Practitioner"
* entry[=].resource = 4-2-Practitioner
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/5-2-Organization"
* entry[=].resource = 5-2-Organization
* entry[+].fullUrl = "http://test.fhir.ch/r4/PractitionerRole/6-3-PractitionerRole"
* entry[=].resource = 6-3-PractitionerRole
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/4-3-Practitioner"
* entry[=].resource = 4-3-Practitioner
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/5-3-Organization"
* entry[=].resource = 5-3-Organization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-2-Immunization"
* entry[=].resource = 7-2-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-3-Immunization"
* entry[=].resource = 7-3-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-4-Immunization"
* entry[=].resource = 7-4-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-5-Immunization"
* entry[=].resource = 7-5-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Immunization/7-6-Immunization"
* entry[=].resource = 7-6-Immunization
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/8-2-Condition"
* entry[=].resource = 8-2-Condition
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/8-3-Condition"
* entry[=].resource = 8-3-Condition
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/8-4-Condition"
* entry[=].resource = 8-4-Condition
* entry[+].fullUrl = "http://test.fhir.ch/r4/AllergyIntolerance/11-1-AllergyIntolerance"
* entry[=].resource = 11-1-AllergyIntolerance
* entry[+].fullUrl = "http://test.fhir.ch/r4/AllergyIntolerance/11-2-AllergyIntolerance"
* entry[=].resource = 11-2-AllergyIntolerance
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/8-9-Condition"
* entry[=].resource = 8-9-Condition
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/9-1-Observation"
* entry[=].resource = 9-1-Observation
* entry[+].fullUrl = "http://test.fhir.ch/r4/Condition/8-1-Condition"
* entry[=].resource = 8-1-Condition
* entry[+].fullUrl = "http://test.fhir.ch/r4/ImmunizationRecommendation/10-2-ImmunizationRecommendation"
* entry[=].resource = 10-2-ImmunizationRecommendation
* entry[+].fullUrl = "http://test.fhir.ch/r4/ImmunizationRecommendation/10-1-ImmunizationRecommendation"
* entry[=].resource = 10-1-ImmunizationRecommendation